version: 2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    parameters:
      pw_db:
        type: string
        default: kegg
    resource_class: small
    steps:
      - run: echo << parameters.pw_db >>
      - run: |
          circleci tests glob << parameters.pw_db >>/** | circleci tests split > /tmp/tests-to-run
          cat /tmp/tests-to-run

