version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    parameters:
      pw_db:
        type: string
        default: 'kegg'
    resource_class: small
    parallelism: 10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 0b:40:cc:78:9a:25:bb:ae:84:1b:ac:cb:68:f3:97:98
#      - run: echo << parameters.pw_db >>
      - run: |
          circleci tests glob << parameters.pw_db >>/*.txt | circleci tests split > /tmp/tests-to-run
          cat /tmp/tests-to-run
          python main.py
      - run: |
          ls
          ls distributions/<< parameters.pw_db >>
      - run: |
          git pull
          git config --global user.email "anna.pamela@gmail.com"
          git config --global user.name "annapamma"
          git add distributions
          git commit --allow-empty -m "test push"
          git push


workflows:
  test:
    jobs:
      - build:
          pw_db: 'xcell'
