version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    parameters:
      pw_db:
        type: string
        default: 'kegg'
    resource_class: small
    parallelism: 10
    steps:
      - checkout
      - run: echo << parameters.pw_db >>
      - run: |
          circleci tests glob << parameters.pw_db >>/*.txt | circleci tests split > /tmp/tests-to-run
          cat /tmp/tests-to-run

workflows:
  test:
    jobs:
      - build:
          pw_db: 'xcell'
